/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;
import clases.Conexion;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;
/**
 *
 * @author Kirizu
 */
public class ReporteGrafico extends javax.swing.JFrame {
     
     String dia = "", mes = "" ,año = "";
     
    /**
     * Creates new form ReporteGrafico
     */
    public ReporteGrafico() {
        initComponents();
        mostrarDatos();
        setLocationRelativeTo(null);
        for (int i = 2020; i > 2000; i--) {
            String año =  String.valueOf(i);
            cmbAño.addItem(año);
        }
    }
    
    public void mostrarDatos(){
    DefaultTableModel modelo = new DefaultTableModel();
      modelo.addColumn("FECHA");
      modelo.addColumn("FACTURAS");
      modelo.addColumn("PRODUCTOS");
      modelo.addColumn("CANTIDAD");
      modelo.addColumn("INGRESO");
      String fecha = "";
        if (cmbDia.getSelectedItem().equals("-Seleccione un día-") && cmbMes.getSelectedItem().equals("-Seleccione un mes-") && cmbAño.getSelectedItem().equals("-Seleccione un año-")) {
       dia = "";
       mes = "";
       año = ""; 
        }else{
       dia = cmbDia.getSelectedItem().toString().trim();
       mes = cmbMes.getSelectedItem().toString().trim();
       año = cmbAño.getSelectedItem().toString().trim(); 
      fecha="where fecha like 'Cuenca, "+dia+" / "+mes+" / "+año+"'";
        }
    
       String Dato[] = new String[5];
       
       try {
       Connection cn = Conexion.conectar();
      PreparedStatement pst = cn.prepareStatement("select fecha FECHA, numeroDocumento FACTURAS, productos PRODUCTOS, count(productos) CANTIDAD, count(productos)*precioUnitario INGRESO from registroventas "+fecha+" group by productos");
       ResultSet rs = pst.executeQuery();
       
           while (rs.next()) {               
               Dato[0] = rs.getString(1);
               Dato[1] = rs.getString(2);
               Dato[2] = rs.getString(3);
               Dato[3] = rs.getString(4);
               Dato[4] = "$ "+rs.getString(5);
               modelo.addRow(Dato);
           }
           tbReporte.setModel(modelo);
       
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbDia = new javax.swing.JComboBox<>();
        cmbMes = new javax.swing.JComboBox<>();
        cmbAño = new javax.swing.JComboBox<>();
        btnGrafico = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbReporte = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Reporte Gráfico");

        cmbDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seleccione un día-", "1", "2", "3", "4", "5", "6", "7" }));

        cmbMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seleccione un mes-", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", " " }));
        cmbMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMesActionPerformed(evt);
            }
        });

        cmbAño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seleccione un año-" }));

        btnGrafico.setText("Grafico");
        btnGrafico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficoActionPerformed(evt);
            }
        });

        tbReporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "FECHA", "FACTURA", "PRODUCTOS", "CANTIDAD", "INGRESO"
            }
        ));
        jScrollPane1.setViewportView(tbReporte);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGrafico)))
                .addContainerGap(256, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGrafico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGraficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficoActionPerformed
       
       
            /*DefaultCategoryDataset dtsc = new DefaultCategoryDataset();
            for (int i=0;i<tbReporte.getRowCount();i++)
            {
                dtsc.setValue(Integer.parseInt(tbReporte.getValueAt(i, 2).toString()), tbReporte.getValueAt(i, 3).toString(), tbReporte.getValueAt(i, 4).toString());
            }
            
            JFreeChart ch = ChartFactory.createBarChart3D("Gráfica de Barras 3D", "Dias", "Cantidad", dtsc, PlotOrientation.VERTICAL, true, true, false);
            ChartPanel cp =  new ChartPanel(ch);
            add(cp);
            cp.setBounds(600,80,500,500);*/
            
                 DefaultCategoryDataset dtsc= new DefaultCategoryDataset();
                for (int i = 0; i < tbReporte.getRowCount(); i++) {
                    dtsc.setValue(Integer.parseInt(tbReporte.getValueAt(i,2).toString()), tbReporte.getValueAt(i,4).toString(), tbReporte.getValueAt(i,4).toString());
                }
            
                JFreeChart ch=ChartFactory.createBarChart3D("Grafica de Barras 3D", "Fecha", "Cantidad", dtsc, PlotOrientation.VERTICAL,true,true,false);
                ChartPanel cp= new ChartPanel(ch);
                add(cp);
                cp.setBounds(800,100,400,400);
 //mostrarDatos();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnGraficoActionPerformed

    private void cmbMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReporteGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReporteGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReporteGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReporteGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReporteGrafico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGrafico;
    private javax.swing.JComboBox<String> cmbAño;
    private javax.swing.JComboBox<String> cmbDia;
    private javax.swing.JComboBox<String> cmbMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbReporte;
    // End of variables declaration//GEN-END:variables
}
